// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://clgherbgwsmonuudztvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZ2hlcmJnd3Ntb251dWR6dHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTQyOTcsImV4cCI6MjA2ODc3MDI5N30.Jmc2nA5JwofnGoON7OHa84PLfSUX60iyEa6FZZ66SUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);